message/urls.py
# -*- encoding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from .views import (
    ConversationsListView,
    LikeConversationView,
    MessageDetailView,
    NewConversationView,
    ReportedDetailView,
    ReportedListView,
    ReportView,
    ReportedOveruledView,
    ReportedPostponeView,
    ReportedSustainedView,
    UnLikeConversationView,
)


urlpatterns = [
    url(
        regex=r"^conversations/(?P<pk>\d+)/$",
        view=ConversationsListView.as_view(),
        name="conversation.list",
    ),
    url(
        regex=r"^conversations/$",
        view=ConversationsListView.as_view(),
        name="conversation.list",
    ),
    url(
        regex=r"^conversations/new/$",
        view=NewConversationView.as_view(),
        name="conversations.new",
    ),
    url(
        regex=r"^message/(?P<pk>\d+)/$",
        view=MessageDetailView.as_view(),
        name="message.detail",
    ),
    url(
        regex=r"^like/(?P<pk>\d+)/$",
        view=LikeConversationView.as_view(),
        name="conversation.message.like",
    ),
    url(
        regex=r"^unlike/(?P<pk>\d+)/$",
        view=UnLikeConversationView.as_view(),
        name="conversation.message.unlike",
    ),
    url(
        regex=r"^reported/$",
        view=ReportedListView.as_view(),
        name="reported.list",
    ),
    url(
        regex=r"^reported/detail/(?P<pk>\d+)/$",
        view=ReportedDetailView.as_view(),
        name="reported.detail",
    ),
    url(
        regex=r"^report/(?P<pk>\d+)/$",
        view=ReportView.as_view(),
        name="reported.report",
    ),
    url(
        regex=r"^overrule/(?P<pk>\d+)/$",
        view=ReportedOveruledView.as_view(),
        name="reported.overruled",
    ),
    url(
        regex=r"^sustain/(?P<pk>\d+)/$",
        view=ReportedSustainedView.as_view(),
        name="reported.sustained",
    ),
    url(
        regex=r"^postpone/(?P<pk>\d+)/$",
        view=ReportedPostponeView.as_view(),
        name="reported.postpone",
    ),
]

message/models.py
# -*- encoding: utf-8 -*-
import re
from dateutil.parser import parse
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.db import connections, models
from django.db.models import Count, Max, Q
from django.urls import reverse
from reversion import revisions as reversion
from base.model_utils import TimedCreateModifyDeleteModel
from contact.models import Contact


class MessageError(Exception):
    def __init__(self, value):
        Exception.__init__(self)
        self.value = value

    def __str__(self):
        return repr("{}, {}".format(self.__class__.__name__, self.value))


class MessageManager(models.Manager):
    def create_message(self, **kwargs):
        obj = self.model(**kwargs)
        obj.save()
        return obj

    def current(self):
        return self.model.objects.exclude(deleted=True)

    def messages_to(self, message_to, message_type):
        """Finds all the tributes, etc given to a person."""
        return (
            self.current()
            .filter(message_to=message_to, message_type=message_type)
            .order_by("-created")
        )

    def messages_type(self, message_type):
        """Finds all the messages of a given type."""
        return (
            self.current()
            .filter(message_type=message_type)
            .order_by("-created")
        )

    def conversation(self, converser, conversee):
        """Finds all the messages between two given users."""
        conversation = self.current().filter(
            (Q(message_from=converser) & Q(message_to=conversee))
            | (Q(message_to=converser) & Q(message_from=conversee)),
            message_type=self.model.MESSAGE_TYPE_PRIVATE,
        )
        return conversation

    def message_conversation(self, converser, message_id):
        """Finds all the messages with just a single message_id."""
        message = self.model.objects.get(id=message_id)
        # Only do this if the converser is valid!
        if (
            message.message_from.id == converser.id
            or message.message_to.id == converser.id
        ):
            conversee = message.message_from
            if converser.id == conversee.id:
                conversee = message.message_to
            return self.conversation(converser, conversee)
        return []

    def conversations(self, converser):
        """Finds all other users this person is in a conversation with."""
        rows = []
        if converser:
            with connections["default"].cursor() as cursor:
                cursor.execute(
                    """
                    SELECT
                    	MAX(id) as id
                    FROM message_message
                    WHERE
                    	(
                           message_from_id = %s OR
                	       message_to_id = %s
                        ) AND message_type=%s
                        AND deleted=false
                    GROUP BY
                    	CASE message_to_id
                    	  WHEN %s THEN message_from_id
                    	  ELSE message_to_id
                    	END;
                    """,
                    [
                        converser.pk,
                        converser.pk,
                        Message.MESSAGE_TYPE_PRIVATE,
                        converser.pk,
                    ],
                )
                rows = cursor.fetchall()
        last_messages = [m[0] for m in rows]
        return self.current().filter(id__in=last_messages).order_by("-created")


class Message(TimedCreateModifyDeleteModel):
    """Message model."""

    MESSAGE_TYPE_PRIVATE = "Private"
    MESSAGE_TYPE_PUBLIC = "Public"

    message_types = (
        (MESSAGE_TYPE_PRIVATE, "Private"),
        (MESSAGE_TYPE_PUBLIC, "Public"),
    )

    message_from = models.ForeignKey(
        Contact, related_name="message_from_contact", on_delete=models.CASCADE
    )
    message_to = models.ForeignKey(
        Contact,
        related_name="message_to_contact",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    message = models.TextField(blank=True, null=True)
    message_style = models.CharField(
        max_length=20, default="plain", blank=True, null=True
    )
    message_type = models.CharField(
        max_length=20, default=MESSAGE_TYPE_PRIVATE, blank=False, null=False
    )
    picture = models.ImageField(upload_to="message", blank=True, null=True)
    is_public = models.BooleanField(default=False)

    objects = MessageManager()

    class Meta:
        ordering = ["created", "pk"]
        verbose_name = "Message"
        verbose_name_plural = "Messages"

    def __str__(self):
        return "{} to {}: {}".format(
            self.message_to, self.message_from, self.message
        )

    def actions(self):
        """Returns all the actions for this message."""
        return self.messageaction_set.exclude(deleted=True)

    def actions_of_type(self, action_name):
        """Returns all the actions for this message."""
        return self.actions().filter(action_name=action_name)

    def action_summary(self):
        """Return a summary grouped by actions for this message."""
        return (
            self.actions()
            .values("action_name")
            .annotate(total=Count("action_name"))
            .order_by("action_name")
        )

    def actions_by(self, action_by):
        """Returns all the actions on this message for the given contact."""
        return self.actions().filter(action_by=action_by)

    def was_actioned_by(self, action_by, action_name):
        """Tells you whether a contact performed the given action for a
        message."""
        return (
            self.actions_by(action_by).filter(action_name=action_name).count()
            > 0
        )

    def get_mentions(self, url_path):
        """Gets the IDs of any users mentioned in this message."""
        if self.message:
            mentions = [
                re.compile(r"[^\d]+").sub("", i)
                for i in re.findall(
                    "{}[\"'\/](\d+)[\"'\>]".format(url_path), self.message
                )
            ]
            return sorted(list(set([int(m) for m in mentions if m])))
        else:
            return []

    def get_multi_as_dict(self):
        """Return the contact multi models as a dictionary.

        .. note:: For use in a view context.

        """
        return dict(actions=self.actions().order_by("pk"))

    # def get_absolute_url(self):
    #     return reverse("conversation.list", args=[self.message_to.pk])

    def set_deleted(self, user):
        super().set_deleted(user)

    def undelete(self):
        super().undelete()


reversion.register(Message)


class MessageActionManager(models.Manager):
    def current(self):
        return self.model.objects.exclude(deleted=True)

    def add_message_action(self, message, action_by, action_for, action_name):
        """Add an action just once for a message, contact and name."""
        obj = None
        try:
            obj = self.model.objects.get(
                message=message,
                action_by=action_by,
                action_for=action_for,
                action_name=action_name,
            )
            # Take as a reason to undelete this.
            if obj.is_deleted:
                obj.undelete()
        except self.model.DoesNotExist:
            obj = self.model(
                message=message,
                action_by=action_by,
                action_for=action_for,
                action_name=action_name,
            )
            obj.save()
        return obj

    def del_message_action(self, message, action_by, action_for, action_name):
        """Delete an action given message, action_by, action_for and name."""
        obj = None
        try:
            obj = self.model.objects.get(
                message=message,
                action_by=action_by,
                action_for=action_for,
                action_name=action_name,
            )
        except self.model.DoesNotExist:
            pass  # It's okay. No action to delete!
        if obj and not obj.is_deleted:
            obj.delete()
        return obj

    def actions_for(self, action_for, action_name=None):
        """Return all actions to action_for which have not been dimissed."""
        rtn = None
        if action_name:
            rtn = self.model.objects.filter(
                action_for=action_for, action_name=action_name, dismissed=False
            )
        else:
            rtn = self.model.objects.filter(
                action_for=action_for,
                action_name__in=settings.NOTIFIABLE_ACTIONS,
                dismissed=False,
            )
        return rtn

    def actions_for_summary(self, action_for, action_name=None):
        """Return a summary per action_for grouped by actions."""
        return (
            self.actions_for(action_for, action_name)
            .values("action_name")
            .annotate(total=Count("action_name"))
            .order_by("action_name")
        )


class MessageAction(TimedCreateModifyDeleteModel):
    """MessageAction model."""

    # RECORDS of ACTIONS
    BOOKMARK = "Bookmark"  # BOOKMARK a message
    OVERRULE = "Overrule"  # OVERRULE a REPORT
    POSTPONE = "Postpone"  # POSTPONE a REPORT
    REPORT = "Report"  # REPORT a message
    SUSTAIN = "Sustain"  # SUSTAIN a REPORT
    VIEW = "View"  # Record a message VIEW

    # NOTIFICATIONS
    LIKED = "Liked"  # Notify when LIKED
    MENTIONED = "Mentioned"  # Notify when MENTIONED
    REPLIED = "Replied"  # Notify when REPLIED
    ADDED = "Added"  # Notify when ADDED
    REPORTED = "Reported"  # Notify when REPORTED

    message = models.ForeignKey(
        Message, on_delete=models.CASCADE, blank=True, null=True
    )
    action_by = models.ForeignKey(
        Contact,
        related_name="action_by_contact",
        on_delete=models.CASCADE,
        blank=True,

message/templates/message/_conversation_link.html
<li class="pure-menu-item {% if contact.pk == conversee.pk %}pure-menu-selected{% endif %}">
  <a href="{% url 'conversation.list' contact.pk %}" class="pure-menu-link">
    {{ contact.full_name }} - {{ message.created|date:'d/m/Y H:i' }}
  </a>
</li>

message/templates/message/_conversation_list.html
{% if conversation %}
<div class="pure-g">
  {% for message in conversation %}

  {% if message.message_from.pk == conversee.pk %}
  <div class="pure-u-1-5">
    <!--  Moves the chat box to the right when not the user logged in. -->
    &nbsp;
  </div>
  {% endif %}
  <div class="pure-u-4-5 conversation">

    {% if message.picture %}
      <a href="{{ message.picture.url }}" target="img">
        <img class="pure-img" src="{{ message.picture.url }}" />
      </a>
    {% endif %}
    <p>
      {% if message.message %}
        {{ message.message }}
        <br>
      {% endif %}
      <span class="small">
        {{ message.message_from.first_name }}
        {{ message.message_from.last_name }} -
        {{ message.created }}</span>
      <span class="small"  style="float: right;">
        {% for action in message.action_summary %}
          {{ action.action_name }} {{ action.total }}
        {% endfor %}

        {% if message.was_liked %}
          <a href="{% url 'conversation.message.unlike' message.id %}">Unlike</a>
        {% else %}
          <a href="{% url 'conversation.message.like' message.id %}">Liked</a>
        {% endif %}
        {% if not message.was_reported %}
          |
          <a href="{% url 'reported.report' message.id %}">Report</a>
        {% endif %}
      </span>
    </p>

    <p>
    </p>
  </div>
  <div class="pure-u-1">
    <!--  Empty and Forces a new line.
      Cos: We always want <div class="pure-u-1-5"> to be first in the row. -->
  </div>

  {% endfor %}

  <div class="pure-u-1">
    {% include '_form.html' with legend='Message '|add:conversee.full_name aligned=False multipart=True %}
  </div>

</div>

{% else %}

<p><i>Select a conversation with one of your contacts.</i></p>

{% endif %}

message/templates/message/_conversations_list.html
<div class="pure-menu">
  <ul class="pure-menu-list">
  {% for message in conversations %}
    {% if message.message_from.pk == active_user.pk %}
      {% include 'message/_conversation_link.html' with contact=message.message_to %}
    {% else %}
      {% include 'message/_conversation_link.html' with contact=message.message_from %}
    {% endif %}
  {% endfor %}
  </ul>
</div>

message/templates/message/_message_detail.html
<tr>
  <thead>
    <th colspan="2">
      <strong>Message</strong>
    </th>
  </thead>
</tr>
<tr>
  <td colspan="2">
    {% if message.message %}
      <div>
        {{ message.message }}
      </div>
    {% endif %}
    {% if message.picture %}
    <p>
        <img src="/media/{{ message.picture }}" class="pure-img" />
    </p>
    {% endif %}
  </td>
</tr>
<tr>
  <th>
    messageTo
  </th>
  <td>
    <a href="{% url 'contact.update' message.message_to.pk %}">
      <i class="fa fa-edit"></i>
      {{ message.message_to.get_full_name }}
    </a>
    <small>
      ({{ message.message_to.user.username }})
    </small>
  </td>
</tr>
<tr>
  <th>
    messageFrom
  </th>
  <td colspan="2">
    <a href="{% url 'contact.update' message.message_from.pk %}">
      <i class="fa fa-edit"></i>
      {{ message.message_from.get_full_name }}
    </a>
    <small>
      ({{ message.message_from.user.username }})
    </small>
  </td>
</tr>
<tr>
  <th>
    Reported By
  </th>
  <td colspan="2">
    {% for ma in actions %}
      <a href="{% url 'contact.update' message.message_to.pk %}">
        [{{ ma.action_by.get_full_name }} <small>{{ma.action_name}}</small>]
      </a>
    {% endfor %}
  </td>
</tr>

message/templates/message/_message_list.html
<table class="pure-table pure-table-bordered" width="100%">
  <thead>
    <tr>
      <th>Message</th>
      <th>MessageFrom</th>
      <th>MessageTo</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    {% for message in message_list %}
      <tr valign="top">
        <td>
          {{ message.message }}
        </td>
        <td>
          <a href="{% url 'contact.update' message.message_to.pk %}">
            {{ message.message_to }}
          </a>
        </td>
        <td>
          <a href="{% url 'contact.update' message.message_from.pk %}">
            {{ message.message_from }}
          </a>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

message/templates/message/_reported_list.html
<table class="pure-table pure-table-bordered" width="100%">
  <thead>
    <tr>
      <th>Message</th>
      <th>MessageFrom</th>
      <th>MessageTo</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    {% for message in message_list %}
      <tr valign="top">
        <td>
          {{ message.message }}
        </td>
        <td>
          <a href="{% url 'contact.update' message.message_to.pk %}">
            <i class="fa fa-edit"></i> {{ message.message_to }}
          </a>
        </td>
        <td>
          <a href="{% url 'contact.update' message.message_from.pk %}">
            <i class="fa fa-edit"></i> {{ message.message_from }}
          </a>
        </td>
        <td>
          <a href="{% url 'reported.detail' message.pk %}">
            <i class="fa fa-edit"></i> Action
          </a>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

message/templates/message/base.html
{% extends 'dash/base.html' %}

message/templates/message/conversation_list.html
{% extends 'message/base.html' %}

{% block content %}
<style>
  .conversations {
    background-color: lightgrey;
    box-sizing: border-box;
    padding: 12px;
  }
  .conversation {
    box-sizing: border-box;
    padding: 10px 20px;
    margin-bottom: 20px;
    background-color: #1f8dd6;
    color: white;
  }
  .conversation a {
    color: lightgrey;
    text-decoration: underline;
  }
  .small {
    font-size: 80%;
    color: lightgrey;
  }
  .pure-menu-selected {
    font-weight: bold;
    background-color: lightgrey;
  }
</style>

<div class="pure-g">
  <div class="pure-u-1 pure-u-sm-1-3">
    <h3>Your conversations</h3>
    {% include 'message/_conversations_list.html' %}
    <p>
      <a href="{% url 'conversations.new' %}" class="pure-button">
        Start a new conversation
      </a>
    </p>
  </div>
  <div class="pure-u-1 pure-u-sm-2-3 conversations">
    {% include 'message/_conversation_list.html' %}
  </div>
</div>
{% endblock content %}

message/templates/message/message_detail.html
{% extends 'dash/base.html' %}

{% block sub_title %}
  Reported Message
{% endblock sub_title %}

{% block sub_heading %}
  Reported Message
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          <li class="pure-menu-item">
            <a href="{% url 'conversation.list' %}" class="pure-menu-link">
              <i class="fa fa-reply"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1 pure-u-md-1-2">
      <div class="r-box">
        <table width="100%" class="pure-table pure-table-bordered">
          <tbody>
            {% include 'message/_message_detail.html' %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}

message/templates/message/message_list.html
{% extends 'message/base.html' %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      {% include 'message/_message_list.html' %}
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          {% include 'base/_paginate.html' %}
        </ul>
      </div>
    </div>
  </div>
{% endblock content %}

message/templates/message/message_new.html
{% extends 'message/base.html' %}


{% block content %}
  <div class="pure-u-1">
    {% include '_form.html' with legend='Message' aligned=True multipart=True %}
  </div>
{% endblock content %}

message/templates/message/reported_detail.html
{% extends 'dash/base.html' %}

{% block sub_title %}
  Reported Message
{% endblock sub_title %}

{% block sub_heading %}
  Reported Message
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          <li class="pure-menu-item">
            <a href="{% url 'reported.list' %}" class="pure-menu-link">
              <i class="fa fa-reply"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1 pure-u-md-1-2">
      <div class="r-box">
        <table width="100%" class="pure-table pure-table-bordered">
          <tbody>
            {% include 'message/_message_detail.html' %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="pure-u-1 pure-u-md-1-2">
      <table width="100%" class="pure-table pure-table-bordered">
        <thead>
          <tr>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <a href="{% url 'reported.overruled' message.id %}" class="pure-menu-link">
                <i class="fa fa-thumbs-up"></i> This message is okay. Reports overruled.
              </a>
            </td>
          </tr>
          {% if not message.deleted %}
          <tr>
            <td>
              <a href="{% url 'reported.sustained' message.id %}" class="pure-menu-link">
                <i class="fa fa-thumbs-down"></i> This message is not okay. Reports sustained.
              </a>
            </td>
          </tr>
          {% endif %}
          <tr>
            <td>
              <a href="{% url 'reported.postpone' message.id %}" class="pure-menu-link">
                <i class="fa fa-hourglass-1"></i> Deal with this later.
              </a>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
{% endblock content %}

message/templates/message/reported_list.html
{% extends 'message/base.html' %}

{% block sub_heading %}
  List of Reported Posts
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <p>
        This list only shows reported posts which you have not already dealt with.
      </p>
      {% include 'message/_reported_list.html' %}
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          {% include 'base/_paginate.html' %}
        </ul>
      </div>
    </div>
  </div>
{% endblock content %}